services:
  ao-analytics-nginx:
    container_name: ao-analytics-nginx
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/cache:/var/cache/nginx
    restart: unless-stopped
    depends_on:
      ao-analytics-frontend:
        condition: service_started
      ao-analytics-api:
        condition: service_started

  ao-analytics-db:
    container_name: ao-analytics-db
    build:
      context: ../ao-analytics-db
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ao
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  ao-analytics-migrator:
    container_name: ao-analytics-migrator
    build:
      context: ../ao-analytics-migrator
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@ao-analytics-db:5432/ao
      - LOCATIONS_PATH=data/locations.json
      - ITEMS_PATH=data/items.json
      - LOCALIZATIONS_PATH=data/localizations.json
      - LOCATIONS_URL=https://raw.githubusercontent.com/ao-data/ao-bin-dumps/master/formatted/world.json
      - ITEMS_URL=https://raw.githubusercontent.com/ao-data/ao-bin-dumps/master/items.json
      - LOCALIZATIONS_URL=https://raw.githubusercontent.com/ao-data/ao-bin-dumps/master/formatted/items.json
      - SKIP_DOWNLOAD_IF_EXISTS=false
    volumes:
      - ./migrator:/data
    restart: no
    depends_on:
      ao-analytics-db:
        condition: service_healthy

  ao-analytics-nats:
    container_name: ao-analytics-nats
    build:
      context: ../ao-analytics-nats
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@ao-analytics-db:5432/ao
      - NATS_URL=nats://public:thenewalbiondata@nats.albion-online-data.com:34222
      - NATS_MARKET_ORDER_SUBJECT=marketorders.deduped
      - NATS_MARKET_HISTORY_SUBJECT=markethistories.deduped
      - NATS_USER=public
      - NATS_PASSWORD=thenewalbiondata
    depends_on:
      ao-analytics-db:
        condition: service_healthy
      ao-analytics-migrator:
        condition: service_completed_successfully

  ao-analytics-api:
    container_name: ao-analytics-api
    build:
      context: ../ao-analytics-api
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@ao-analytics-db:5432/ao
      - PORT=80
      - RUST_LOG=3 # trace
    depends_on:
      ao-analytics-db:
        condition: service_healthy

  ao-analytics-frontend:
    container_name: ao-analytics-frontend
    build:
      context: ../ao-analytics-frontend
      dockerfile: Dockerfile
    environment:
      - HOST=0.0.0.0
      - PORT=80
      - PUBLIC_BACKEND_URL=http://api.localhost
      - PUBLIC_RENDER_URL=https://render.albiononline.com
      - PUBLIC_INTERNAL_URL=http://ao-analytics-api
    restart: unless-stopped
    depends_on:
      ao-analytics-api:
        condition: service_started
