server {
    listen 80;

    server_name staging.veqox.dedyn.io;

	location /.well-known/acme-challenge/ {
		root /var/www/certbot;
	}

	if ($host = staging.veqox.dedyn.io) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    return 302 https://$server_name$request_uri;
}

server {
    listen 443 ssl;

    ssl_certificate /etc/nginx/ssl/live/staging.veqox.dedyn.io/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/nginx/ssl/live/staging.veqox.dedyn.io/privkey.pem; # managed by Certbot
    #include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    #ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

    server_name staging.veqox.dedyn.io;
    #proxy_cache api-cache;

    location / {
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_connect_timeout 300;
        proxy_set_header Connection "";

        proxy_pass http://ao-analytics-frontend;
    }
}

server {
    listen 443 ssl;

    ssl_certificate /etc/nginx/ssl/live/staging.veqox.dedyn.io/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/nginx/ssl/live/staging.veqox.dedyn.io/privkey.pem; # managed by Certbot
    #include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    #ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

    server_name api.staging.veqox.dedyn.io;
    #proxy_cache api-cache;

    location / {
	proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_connect_timeout 300;
        proxy_set_header Connection "";

	proxy_cache_valid any 1m;
        proxy_cache_min_uses 3;
        proxy_cache_bypass $cookie_nocache $arg_nocache$arg_comment;

        proxy_pass http://ao-analytics-api:8080;
    }
}
